server.port=8081

spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/protocologov
spring.datasource.username=postgres
spring.datasource.password=Betel328.
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/protocologov