spring.application.name=protocolo-gov

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/protocologov
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Betel328.

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Keycloak (Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/protocologov
